baseurl             = "https://davidhampgonsalves.github.io/"
builddrafts         = true
canonifyurls        = true
contentdir          = "content"
languageCode        = "en-US"
layoutdir           = "layouts"
publishdir          = "public"
author              = "David Hamp-Gonsalves"
title               = "David Hamp-Gonsalves"
theme               = "black-and-light"

[[menu.main]]
    name = "GitHub"
    url = "//github.com/davidhampgonsalves"
[[menu.main]]
    name = "Projects"
    url = "/Projects"
[[menu.main]]
    name = "Resume"
    url = "/html/resume.html"

pygmentscodefences  = true
pygmentsstyle       = "bw"

pluralizelisttitles = false
googleAnalytics     = "UA-123-45"

[permalinks]
posts = ":slug/"

[params]
sitename      = "David Hamp-Gonsalves"
dateform     = "January 2006"
dateformfull = "Mon Jan 2 2006"
